---

- name: Small task set
  hosts: all
  tasks:
  - name: Install apache
    yum:
      name: apache2
      state: present

  - name: Restart apache
    service:
      name: apache2
      state: started
      enabled: yes
